-- ============================================================================
-- TECHOPEDIA LEVEL 15 // IEEE SIESGST
-- Theme: Marvel Multiverse of Tech
-- Team Access Control, RBAC, Audit Logging & Security Policies
-- ============================================================================

-- 1. Enable required extensions
create extension if not exists "pgcrypto";

-- 2. Create `team_members` table
create table if not exists public.team_members (
    id bigint generated by default as identity primary key,
    user_id uuid unique,
    name text not null,
    email text unique not null,
    role text not null check (role in ('super_admin', 'coordinator', 'scanner', 'viewer')) default 'viewer',
    department text default 'General Operations',
    active boolean not null default true,
    last_login timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- 3. Create `team_audit_logs` table
create table if not exists public.team_audit_logs (
    id bigint generated by default as identity primary key,
    user_id uuid,
    user_name text,
    user_email text,
    user_role text,
    action text not null,
    target_id text,
    details jsonb default '{}'::jsonb,
    ip_address text,
    created_at timestamptz not null default now()
);

-- 4. Add check-in status columns to `students` table if not already present
do $$
begin
    if not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'students' and column_name = 'checked_in') then
        alter table public.students add column checked_in boolean not null default false;
    end if;

    if not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'students' and column_name = 'checked_in_at') then
        alter table public.students add column checked_in_at timestamptz;
    end if;

    if not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'students' and column_name = 'checked_in_by') then
        alter table public.students add column checked_in_by text;
    end if;
end $$;

-- 5. Performance Indexes
create index if not exists idx_team_members_user_id on public.team_members (user_id);
create index if not exists idx_team_members_email on public.team_members (email);
create index if not exists idx_team_members_role on public.team_members (role);
create index if not exists idx_team_audit_logs_action on public.team_audit_logs (action);
create index if not exists idx_team_audit_logs_created_at on public.team_audit_logs (created_at desc);
create index if not exists idx_students_checked_in on public.students (checked_in);

-- 6. Enable Row Level Security (RLS)
alter table public.team_members enable row level security;
alter table public.team_audit_logs enable row level security;

-- Helper function to check if the executing user is a super_admin
create or replace function public.is_super_admin()
returns boolean as $$
begin
    return exists (
        select 1 from public.team_members
        where user_id = auth.uid()
        and role = 'super_admin'
        and active = true
    );
end;
$$ language plpgsql security definer;

-- Helper function to check if the executing user is any active team member
create or replace function public.is_active_team_member()
returns boolean as $$
begin
    return exists (
        select 1 from public.team_members
        where user_id = auth.uid()
        and active = true
    );
end;
$$ language plpgsql security definer;

-- 7. Policies for `team_members`
drop policy if exists "Team members can view active team directory" on public.team_members;
create policy "Team members can view active team directory"
on public.team_members for select
to authenticated
using (public.is_active_team_member());

drop policy if exists "Only Super Admins can insert team members" on public.team_members;
create policy "Only Super Admins can insert team members"
on public.team_members for insert
to authenticated
with check (public.is_super_admin());

drop policy if exists "Only Super Admins can update team members" on public.team_members;
create policy "Only Super Admins can update team members"
on public.team_members for update
to authenticated
using (public.is_super_admin())
with check (public.is_super_admin());

drop policy if exists "Only Super Admins can delete team members" on public.team_members;
create policy "Only Super Admins can delete team members"
on public.team_members for delete
to authenticated
using (public.is_super_admin());

-- 8. Policies for `team_audit_logs`
drop policy if exists "Team members can view audit logs" on public.team_audit_logs;
create policy "Team members can view audit logs"
on public.team_audit_logs for select
to authenticated
using (public.is_active_team_member());

drop policy if exists "Team members can insert audit logs" on public.team_audit_logs;
create policy "Team members can insert audit logs"
on public.team_audit_logs for insert
to authenticated
with check (public.is_active_team_member());

-- ============================================================================
-- BOOTSTRAP: Seed Siddharth Patil (Technical Head) as Super Admin
-- ============================================================================

-- Method 1: If creating/elevating by Email (Automatic user_id linking on login):
insert into public.team_members (name, email, role, department, active)
values (
  'Siddharth Patil',
  'siddharth.patil@ieee-siesgst.ac.in', -- Set to Siddharth's exact login email
  'super_admin',
  'Technical Head',
  true
)
on conflict (email) do update
set role = 'super_admin',
    department = 'Technical Head',
    name = 'Siddharth Patil',
    active = true;

-- Method 2: If you already created the user in Supabase Authentication -> Users:
-- Find Siddharth's User UID and link it directly:
--
-- update public.team_members
-- set user_id = 'YOUR-AUTH-USER-UID'::uuid,
--     role = 'super_admin',
--     department = 'Technical Head',
--     active = true
-- where email = 'siddharth.patil@ieee-siesgst.ac.in';
-- ============================================================================
